services:
  - type: web
    name: news-monkey-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GNEWS_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false